test:
	node ../bin/tc case
	node ../bin/tc case.exec
	node ../bin/tc case.before-after
	node ../bin/tc case.commands
	node ../bin/tc case.async
	node ../bin/tc case.async-fail
	node ../bin/tc case.require

.PHONY : test